name = "docs"
uuid = "5e4f2d2a-07f0-4d3a-975f-06685253731d"
version = "0.1.0"
authors = ["Xijiang Yu <xijiang@users.noreply.github.com>"]

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Documenter = "1.17.0"
